# local | dev | prod 환경에 맞게 설정
# application-{environment}.yml
# ./gradlew build 빌드 후 cd build/libs
# java -jar -Dspring.profiles.active={environment} ~.jar

# 예시
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/demo?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
#    username:
#    password:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: create
#      # update : 기존의 스키마를 유지하며 JPA 에 의해 변경된 부분만 추가
#      # validate : Entity 와 Table 이 정상적으로 매핑되어있는지 검증
#      # create : 기존에 존재하는 스키마를 삭제하고 새로 생성
#      # create-drop : 스키마를 생성하고 애플리케이션이 종료될 때 삭제
#      # none : 초기화 동작 X
#    properties:
#      hibernate:
#        format_sql: true
#
#logging:
#  level:
#    org.hibernate.SQL: debug
#    org.hibernate.type: trace