version: "3" # 파일 규격 버전
services: # 이 항목 밑에 실행하려는 컨테이너 들을 정의
  db: # 서비스 명
    image: mysql:latest # 사용할 이미지
    container_name: "demo_mysql" # 컨테이너 이름 설정
    ports:
      - "3306:3306" # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    restart: unless-stopped
    env_file:
      - .env
    environment: # -e 옵션
      # MYSQL_ROOT_PASSWORD: "password"  # MYSQL 패스워드 설정 옵션
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ${PWD}/mysql:/var/lib/mysql # -v 옵션 (다렉토리 마운트 설정)
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

# docker-compose up -d 명령으로 백그라운드에서 실행
# docker exec -i -t demo_mysql bash 명령으로 접속